---
# Source: camunda-platform/charts/tasklist/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-importer-archiver
  labels:
    app.kubernetes.io/component: tasklist-importer-archiver
    app.kubernetes.io/tier: importer-archiver
  annotations:
    {}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: tasklist-importer-archiver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tasklist-importer-archiver
    spec:
      imagePullSecrets:
        []
      containers:
      - name: tasklist-importer
        image: "camunda/tasklist:8.3.0-alpha1"
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/tasklist"
          - name: SPRING_PROFILES_ACTIVE
            value: "identity-auth"
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform"
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/certs"
          - name: CAMUNDA_TASKLIST_IDENTITY_ISSUER_URL
            value: "https://YOUR_HOSTNAME/auth/realms/camunda-platform"
          - name: CAMUNDA_TASKLIST_IDENTITY_ISSUER_BACKEND_URL
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform"
          - name: CAMUNDA_TASKLIST_IDENTITY_CLIENT_ID
            value: "tasklist"
          - name: CAMUNDA_TASKLIST_IDENTITY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "camunda-tasklist-identity-secret"
                key: tasklist-secret
          - name: CAMUNDA_TASKLIST_IDENTITY_AUDIENCE
            value: "tasklist-api"
          - name: CAMUNDA_TASKLIST_IDENTITY_REDIRECT_ROOT_URL
            value: "https://YOUR_HOSTNAME"
          - name: ZEEBE_CLIENT_ID
            value: zeebe
          - name: ZEEBE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "camunda-zeebe-identity-secret"
                key: zeebe-secret
          - name: ZEEBE_AUTHORIZATION_SERVER_URL
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token"
          - name: ZEEBE_TOKEN_AUDIENCE
            value: zeebe-api
          - name: GRAPHQL_PLAYGROUND_ENABLED
            value: "true"
          - name: GRAPHQL_PLAYGROUND_SETTINGS_REQUEST_CREDENTIALS
            value: "include"
          - name: CAMUNDA_TASKLIST_IDENTITY_REDIRECT_ROOT_URL
            value: https://YOUR_HOSTNAME
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 400m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /tasklist/actuator/health/readiness
            scheme: HTTP
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /app/resources/application.yml
          subPath: application.yml
      volumes:
      - name: config
        configMap:
          name: tasklist-configmap-importer-archiver
          defaultMode: 484
