kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: us-east1
  name: chaos-network-brokers
spec:
  selector:
    namespaces:
      - us-east1
    pods:
      us-east1:
        - camunda-zeebe-0
        - camunda-zeebe-1
        - camunda-zeebe-2
        - camunda-zeebe-3
        - camunda-elasticsearch-master-0
        - camunda-elasticsearch-master-1
  mode: all
  action: delay
  delay:
    latency: 50ms
    correlation: '100'
    jitter: '0'
  direction: both
  target:
    selector:
      namespaces:
        - europe-west1
      pods:
        europe-west1:
          - camunda-zeebe-0
          - camunda-zeebe-1
          - camunda-zeebe-2
          - camunda-zeebe-3
          - camunda-elasticsearch-master-0
          - camunda-elasticsearch-master-1
    mode: all