kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: chaos-network-brokers
spec:
  selector:
    namespaces:
      - camunda
    pods:
      camunda:
        - camunda-zeebe-4
        - camunda-zeebe-5
        - camunda-zeebe-6
        - camunda-zeebe-7
  mode: all
  action: delay
  delay:
    latency: 35ms
    correlation: '100'
    jitter: '0'
  direction: both
  target:
    selector:
      namespaces:
        - camunda
      pods:
        camunda:
          - camunda-zeebe-0
          - camunda-zeebe-1
          - camunda-zeebe-2
          - camunda-zeebe-3
    mode: all
