# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  ingress:
    enabled: false
  image:
    tag: latest
    # pullPolicy: Always
  identity:
    auth:
      enabled: true
      publicIssuerUrl: "http://keycloak.aws.c8sm.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "http://operate.aws.c8sm.com"
      tasklist:
        redirectUrl: "http://tasklist.aws.c8sm.com"
      optimize:
        redirectUrl: "http://optimize.aws.c8sm.com"

connectors:
  enabled: false

webModeler:
  enabled: false

optimize:
  enabled: false

#prometheusServiceMonitor:
#  enabled: true

identity:
  enabled: true
  fullURL: "http://identity.aws.c8sm.com"

  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "http://keycloak.aws.c8sm.com/auth"

zeebe-gateway:
  ingress:
    enabled: false
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"


