---
# Source: camunda-platform/charts/identity/charts/keycloak/templates/keycloak-secrets.tpl.yaml
apiVersion: v1
kind: Secret
metadata:
  name: camunda-keycloak
  namespace: "KEYCLOAK_NAMESPACE"
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: "ADMIN_PASSWORD"
  management-password: "MANAGEMENT_PASSWORD"
