apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"us-east1.svc.cluster.local": ["10.142.0.113"], "us-east1-failover.svc.cluster.local": ["10.142.0.113"]}
