apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"us-east1.svc.cluster.local": ["34.148.177.137"], "us-east1-failover.svc.cluster.local": ["34.148.177.137"], "australia-southeast1.svc.cluster.local": ["34.87.255.152"], "australia-southeast1-failover.svc.cluster.local": ["34.87.255.152"]}
