apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"europe-west1-b.svc.cluster.local": ["34.34.141.123"], "europe-west1-b-failover.svc.cluster.local": ["34.34.141.123"]}
