---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: RELEASE-keycloak-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - HOSTNAME

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: RELEASE-keycloak-vs
spec:
  gateways:
    - camunda-keycloak-ingress
  hosts:
    - HOSTNAME
  http:
    - match:
        - uri:
            prefix: /auth
      route:
        - destination:
            port:
              number: 80
            host: RELEASE-keycloak



