apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: RELEASE-operate-vs
spec:
  hosts:
  - "operate.aws.c8sm.com"
  gateways:
  - RELEASE-gateway
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: RELEASE-operate
        port:
          number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https