---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operate-configmap-webapp
  labels:
    app.kubernetes.io/app: operate
    app.kubernetes.io/component: importer-archiver
    app.kubernetes.io/tier: webapp
data:
  application.yml: |
    # Operate configuration file
    camunda.operate:
      archiverEnabled: false
      importerEnabled: false
      migration.migrationEnabled: false
      # ELS instance to store Operate data
      elasticsearch:
        # Cluster name
        clusterName: elasticsearch
        # Host
        host: elasticsearch-master
        # Transport port
        port: 9200
      # Zeebe instance
      zeebe:
        # Broker contact point
        brokerContactPoint: "camunda-zeebe-gateway:26500"
      # ELS instance to export Zeebe data to
      zeebeElasticsearch:
        # Cluster name
        clusterName: elasticsearch
        # Host
        host: elasticsearch-master
        # Transport port
        port: 9200
        # Index prefix, configured in Zeebe Elasticsearch exporter
        prefix: zeebe-record
    logging:
      level:
        ROOT: INFO
        io.camunda.operate: DEBUG
    #Spring Boot Actuator endpoints to be exposed
    management:
      health.elasticsearch.enabled: false
