---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operate
  labels:
    app.kubernetes.io/app: operate
    app.kubernetes.io/component: operate
    app.kubernetes.io/tier: webapp
  annotations:
    {}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: operate
  template:
    metadata:
      labels:
        app.kubernetes.io/app: operate
        app.kubernetes.io/component: operate
    spec:
      imagePullSecrets:
        []
      containers:
      - name: operate
        image: "camunda/operate:8.3.0-alpha3"
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/operate"
          - name: SPRING_PROFILES_ACTIVE
            value: "identity-auth"
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform"
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/certs"
          - name: CAMUNDA_OPERATE_IDENTITY_ISSUER_URL
            value: "https://gke.upgradingdave.com/auth/realms/camunda-platform"
          - name: CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform"
          - name: CAMUNDA_OPERATE_IDENTITY_CLIENT_ID
            value: "operate"
          - name: CAMUNDA_OPERATE_IDENTITY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "camunda-operate-identity-secret"
                key: operate-secret
          - name: CAMUNDA_OPERATE_IDENTITY_AUDIENCE
            value: "operate-api"
          - name: CAMUNDA_OPERATE_IDENTITY_REDIRECT_ROOT_URL
            value: "https://gke.upgradingdave.com"
          - name: ZEEBE_CLIENT_ID
            value: zeebe
          - name: ZEEBE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "camunda-zeebe-identity-secret"
                key: zeebe-secret
          - name: ZEEBE_AUTHORIZATION_SERVER_URL
            value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token"
          - name: ZEEBE_TOKEN_AUDIENCE
            value: zeebe-api
          - name: CAMUNDA_OPERATE_IDENTITY_REDIRECT_ROOT_URL
            value: https://gke.upgradingdave.com
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 600m
            memory: 400Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /operate/actuator/health/readiness
            scheme: HTTP
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /usr/local/operate/config/application.yml
          subPath: application.yml
      volumes:
      - name: config
        configMap:
          name: operate-configmap-webapp
          defaultMode: 484
