# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  ingress:
    enabled: true
    className: nginx
    host: "YOUR_HOSTNAME"
    tls:
      enabled: true
      secretName: "tls-secret"
  image:
    tag: CAMUNDA_VERSION
    # pullPolicy: Always
  identity:
    auth:
      publicIssuerUrl: "https://YOUR_HOSTNAME/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://YOUR_HOSTNAME/operate"
      tasklist:
        redirectUrl: "https://YOUR_HOSTNAME/tasklist"
      optimize:
        redirectUrl: "https://YOUR_HOSTNAME/optimize"
      connectors:
        redirectUrl: "https://YOUR_HOSTNAME/connectors"
      webModeler:
        redirectUrl: "https://YOUR_HOSTNAME/modeler"
  multiregion:
    # number of regions that this Camunda Platform instance is stretched across
    regions: REGIONS
    # unique id of the region. Should start at 0 for easy computation. With 2 regions, you would have region 0 and 1.
    regionId: REGION_ID

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"

connectors:
  enabled: true
  inbound:
    mode: oauth
  contextPath: "/connectors"

#  env:
#    - name: CAMUNDA_OPERATE_CLIENT_USERNAME
#      value: demo
#    - name: CAMUNDA_OPERATE_CLIENT_PASSWORD
#      value: demo

webModeler:
  enabled: true
  contextPath: "/modeler"
  image:
    pullSecrets:
      - name: camunda-docker-registry
  restapi:
    mail:
      fromAddress: YOUR_EMAIL

postgresql:
  enabled: true

#prometheusServiceMonitor:
#  enabled: true

identity:
  contextPath: "/identity"
  fullURL: "https://YOUR_HOSTNAME/identity"

  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://YOUR_HOSTNAME/auth"

zeebe-gateway:
  ingress:
    enabled: true
    className: nginx
    host: "YOUR_HOSTNAME"
    tls:
      enabled: true
      secretName: "tls-secret"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_CLUSTER_INITIALCONTACTPOINTS
      value: "camunda-zeebe-0.camunda-zeebe.camunda-eastus.svc.cluster.local:26502, camunda-zeebe-1.camunda-zeebe.camunda-eastus.svc.cluster.local:26502, camunda-zeebe-0.camunda-zeebe.camunda-canadacentral.svc.cluster.local:26502, camunda-zeebe-1.camunda-zeebe.camunda-canadacentral.svc.cluster.local:26502"
    - name: ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBETIMEOUT
      value: "500ms"

zeebe:
  clusterSize: 4
  partitionCount: 4
  replicationFactor: 4
  pvcSize: 10Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS
      value: "camunda-zeebe-0.camunda-zeebe.NAMESPACE1.svc.cluster.local:26502, camunda-zeebe-1.camunda-zeebe.NAMESPACE1.svc.cluster.local:26502, camunda-zeebe-0.camunda-zeebe.NAMESPACE2.svc.cluster.local:26502, camunda-zeebe-1.camunda-zeebe.NAMESPACE2.svc.cluster.local:26502"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_CLASSNAME
      value: "io.camunda.zeebe.exporter.ElasticsearchExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_URL
      value: "http://camunda-elasticsearch-master-hl.NAMESPACE2.svc.cluster.local:9200"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_INDEX_PREFIX
      value: "zeebe-record"
    - name: ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBETIMEOUT
      value: "500ms"

#elasticsearch:
#  enabled: true
#  imageTag: 7.17.3
#  replicas: 1
#  minimumMasterNodes: 1
#  # Allow no backup for single node setups
#  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
#  resources:
#    requests:
#      cpu: "100m"
#      memory: "512M"
#    limits:
#      cpu: "1000m"
#      memory: "2Gi"







