apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: | # you may select any name here, but it must end with the .server file extension
    NAMESPACE2.svc.cluster.local:53 {
        forward . DNS_IP_ADDRESS
    }

