apiVersion: batch/v1
kind: Job
metadata:
  name: leader-balancer
spec:
  template:
    spec:
      containers:
      - image: "curlimages/curl:7.87.0"
        name: curl
        args: [ "-L", "-v", "-X", "POST", "http://RELEASE_NAME-zeebe-gateway:9600/actuator/rebalance" ]
      restartPolicy: Never