apiVersion: batch/v1
kind: Job
metadata:
  name: zbctl-deploy
spec:
  template:
    spec:
      containers:
      - name: zbctl-deploy
        image: upgradingdave/zbctl
        command: ["zbctl", "--host", "camunda-zeebe-gateway", "--insecure", "--authzUrl", "http://camunda-keycloak/auth/realms/camunda-platform/protocol/openid-connect/token", "--clientId", "zeebe", "--clientSecret", "$(CLIENT_SECRET)" ,"deploy", "/models/CamundaProcess.bpmn"]
        volumeMounts:
        - name: models
          mountPath: /models/CamundaProcess.bpmn
          subPath: CamundaProcess.bpmn
          readOnly: true
        env:
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: camunda-zeebe-identity-secret
                key: zeebe-secret
      volumes:
      - name: models
        configMap:
          name: models
      restartPolicy: Never
