# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

# This is a very small cluster useful for experimenting

global:
  image:
    # allways work with the latest versions in development
    tag: 8.2.0-alpha5
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

tasklist:
  enabled: false

operate:
  enabled: false

identity:
  enabled: false

optimize:
  enabled: false

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"
  env:
    - name: JAVA_TOOL_OPTIONS
      value: "-Dspring.config.additional-location=file:/additional-application-yaml/application.yaml"
  extraVolumeMounts:
    - name: additional-application-yaml
      mountPath: additional-application-yaml
  extraVolumes:
    - name: additional-application-yaml
      configMap:
        name: additional-application-yaml

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  logLevel: ERROR
  env:
    - name: JAVA_TOOL_OPTIONS
      value: "-Dspring.config.additional-location=file:/additional-application-yaml/application.yaml"
  extraVolumeMounts:
    - name: additional-application-yaml
      mountPath: additional-application-yaml
  extraVolumes:
    - name: additional-application-yaml
      configMap:
        name: additional-application-yaml

elasticsearch:
  enabled: false