# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

# This is a cluster with identity and keycloak enabled

global:
  identity:
    auth:
      publicIssuerUrl: "https://keycloak-camunda.apps-crc.testing/auth/realms/camunda-platform"
      identity:
        redirectUrl: "https://identity-camunda.apps-crc.testing"
      operate:
        redirectUrl: "https://operate-camunda.apps-crc.testing"
      tasklist:
        redirectUrl: "https://tasklist-camunda.apps-crc.testing"
      optimize:
        redirectUrl: "https://optimize-camunda.apps-crc.testing"
      webModeler:
        redirectUrl: "https://modeler-camunda.apps-crc.testing"
      console:
        redirectUrl: "https://console-camunda.apps-crc.testing"

operate:
  enabled: true
  readinessProbe:
    scheme: HTTPS
  resources:
    requests:
      cpu: "250m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "1Gi"
  env:
    - name: SERVER_PORT
      value: '8443'
    - name: SERVER_SSL_CERTIFICATE
      value: "/usr/local/ca/tls.crt"
    - name: SERVER_SSL_CERTIFICATEPRIVATEKEY
      value: "/usr/local/ca/tls.key"
    - name: SERVER_SSL_TRUSTCERTIFICATE
      value: "/usr/local/ca/tls.crt"
    - name: SERVER_HTTP2_ENABLED
      value: 'true'
    - name: JAVA_TOOL_OPTIONS
      value: >-
        -Djavax.net.ssl.trustStore=/usr/local/certificates/keycloak.truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    - name: CAMUNDA_OPERATE_ZEEBE_SECURE
      value: "true"
    - name: CAMUNDA_OPERATE_ZEEBE_CERTIFICATEPATH
      value: "/usr/local/ca/tls.crt"
    - name: CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS
      value: "camunda-zeebe-gateway:26500"
  extraVolumes:
    - name: "keystore-secret"
      secret:
        secretName: "keystore-secret"
    - name: "tls-secret"
      secret:
        secretName: "tls-secret"
  extraVolumeMounts:
    - name: "keystore-secret"
      mountPath: "/usr/local/certificates"
    - name: "tls-secret"
      mountPath: "/usr/local/ca"

tasklist:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "1Gi"

identity:
  enabled: true
  fullURL: "https://identity-camunda.apps-crc.testing"
  startupProbe:
    scheme: HTTPS
  readinessProbe:
    scheme: HTTPS
  livenessProbe:
    scheme: HTTPS
  resources:
    requests:
      cpu: "250m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "1Gi"
  env:
    - name: JAVA_TOOL_OPTIONS
      value: "-Djavax.net.ssl.trustStore=/usr/local/certificates/keycloak.truststore.jks -Djavax.net.ssl.trustStorePassword=changeit -Dserver.port=8443 -Dserver.ssl.key-store=/usr/local/certificates/keycloak.keystore.jks -Dserver.ssl.key-store-password=changeit"
  extraVolumes:
    - name: "keystore-secret"
      secret:
        secretName: "keystore-secret"
  extraVolumeMounts:
    - name: "keystore-secret"
      mountPath: "/usr/local/certificates"

identityKeycloak:
  enabled: true
  tls:
    enabled: true
    existingSecret: "keystore-secret"
    keystorePassword: "changeit"
    truststorePassword: "changeit"
  containerSecurityContext:
    fsGroup: "@@null@@"
    runAsUser: "@@null@@"
  podSecurityContext:
    fsGroup: "@@null@@"
    runAsUser: "@@null@@"

identityPostgres:
  enabled: true

optimize:
  enabled: false

connectors:
  enabled: false

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity:
    podAntiAffinity: null
  pvcSize: 10Gi
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

zeebeGateway:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "1Gi"

elasticsearch:
  enabled: true
  securityContext:
    runAsUser: "@@null@@"
  sysctlImage:
    enabled: false
  podSecurityContext:
    fsGroup: "@@null@@"
    runAsUser: "@@null@@"
  master:
    masterOnly: false
    replicaCount: 1
    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    persistence:
      size: "8Gi"
    containerSecurityContext:
      enabled: false
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0