# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

# This is a very small cluster useful for running locally and for development

global:
  image:
    # allways work with the latest versions in development
    tag: latest
  identity:
    auth:
      enabled: true

tasklist:
  # Enabled if true, the tasklist deployment and its related resources are deployed via a helm release
  enabled: true
  # Env can be used to set extra environment variables on each Tasklist container
  env: 
    # Required to enabled tasklist API access while it is not enabled by default
    - name: "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI"
      value: "http://camunda-keycloak:80/auth/realms/camunda-platform"
    - name: "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI"
      value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/certs"

identity:
  enabled: true

optimize:
  enabled: false

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  logLevel: ERROR

elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi